# Store the notation of the website
def notation(): 
	return ['Addoha',
 'AFMA',
 'Afric Indus',
 'Afriquia Gaz',
 'Agma',
 'Akdital',
 'Alliances',
 'Aluminium Maroc',
 'Aradei Capital',
 'ATLANTASANAD',
 'Attijariwafa',
 'Auto Hall',
 'Auto Nejma',
 'BALIMA',
 'BOA',
 'BCP',
 'BMCI',
 'Cartier Saada',
 'CDM',
 'CIH',
 'Ciments Maroc',
 'CMT',
 'Colorado',
 'COSUMAR',
 'CTM',
 'Dari Couspate', 
 'Delta Holding',
 'Disty Technolog',
 'DISWAY',
 'Ennakl',
 'EQDOM',
 'FENIE BROSSETTE',
 'HPS',
 'IBMaroc',
 'Immr Invest',
 'INVOLYS',
 'Jet Contractors',
 'LABEL VIE',
 'LafargeHolcim',
 'Lesieur Cristal',
 'M2M Group',
 'Maghreb Oxygene',
 'Maghrebail',
 'Managem',
 'Maroc Leasing',
 'Maroc Telecom',
 'Microdata',
 'Mutandis',
 'Oulmes',
 'PROMOPHARM',
 'Rebab Company',
 'Res.Dar Saada',
 'Risma',
 'S2M',
 'Sanlam Maroc',
 'SALAFIN',
 'SMI',
 'Stokvis Nord Afr',
 'SNEP',
 'SODEP',
 'Sonasid',
 'SOTHEMA',
 'SRM',
 'Ste Boissons',
 'STROC Indus',
 'TAQA Morocco',
 'TGCC',
 'Timar',
 'Total Maroc',
 'Unimer',
 'Wafa Assur',
 'Zellidja','MASI',"MSI20"]
	
def notation_code():
      return [
    {'name': 'ADDOHA', 'ISIN': 'MA0000011512'},
    {'name': 'AFMA', 'ISIN': 'MA0000012296'},
    {'name': 'AFRIC INDUS', 'ISIN': 'MA0000012114'},
    {'name': 'AFRIQUIA GAZ', 'ISIN': 'MA0000010951'},
    {'name': 'AGMA', 'ISIN': 'MA0000010944'},
    {'name': 'AKDITAL', 'ISIN': 'MA0000012585'},
    {'name': 'ALLIANCES', 'ISIN': 'MA0000011819'},
    {'name': 'ALUMINIUM MAROC', 'ISIN': 'MA0000010936'},
    {'name': 'ARADEI CAPITAL', 'ISIN': 'MA0000012460'},
    {'name': 'ATLANTASANAD', 'ISIN': 'MA0000011710'},
    {'name': 'ATTIJARIWAFA', 'ISIN': 'MA0000012445'},
    {'name': 'AUTO HALL', 'ISIN': 'MA0000010969'},
    {'name': 'AUTO NEJMA', 'ISIN': 'MA0000011009'},
    {'name': 'BALIMA', 'ISIN': 'MA0000011991'},
    {'name': 'BANK OF AFRICA', 'ISIN': 'MA0000012437'},
    {'name': 'BANQUE CENTRALE POPULAIRE', 'ISIN': 'MA0000011884'},
    {'name': 'BMCI', 'ISIN': 'MA0000010811'},
    {'name': 'CARTIER SAADA', 'ISIN': 'MA0000011868'},
    {'name': 'CREDIT DU MAROC', 'ISIN': 'MA0000010381'},
    {'name': 'CREDIT IMMOBILIER ET HOTELIER', 'ISIN': 'MA0000011454'},
    {'name': 'CIMENTS MAROC', 'ISIN': 'MA0000010506'},
    {'name': 'COMPAGNIE MINIERE DE TOUISSIT', 'ISIN': 'MA0000011793'},
    {'name': 'COLORADO', 'ISIN': 'MA0000011934'},
    {'name': 'COSUMAR', 'ISIN': 'MA0000012247'},
    {'name': 'COMPAGNIE DE TRANSPORT AU MAROC', 'ISIN': 'MA0000010340'},
    {'name': 'DARI COUSPATE', 'ISIN': 'MA0000011421'},
    {'name': 'DELTA HOLDING', 'ISIN': 'MA0000011850'},
    {'name': 'DISTY TECHNOLOG', 'ISIN': 'MA0000012536'},
    {'name': 'DISWAY', 'ISIN': 'MA0000011637'},
    {'name': 'ENNAKL', 'ISIN': 'MA0000011942'},
    {'name': 'EQDOM', 'ISIN': 'MA0000010357'},
    {'name': 'FENIE BROSSETTE', 'ISIN': 'MA0000011587'},
    {'name': 'HIGHTECH PAYMENT SYSTEMS', 'ISIN': 'MA0000011611'},
    {'name': 'IBMAROC', 'ISIN': 'MA0000011132'},
    {'name': 'IMMR INVEST', 'ISIN': 'MA0000012387'},
    {'name': 'INVOLYS', 'ISIN': 'MA0000011579'},
    {'name': 'JET CONTRACTORS', 'ISIN': 'MA0000012080'},
    {'name': 'LABEL VIE', 'ISIN': 'MA0000011801'},
    {'name': 'LAFARGEHOLCIM', 'ISIN': 'MA0000012320'},
    {'name': 'LESIEUR CRISTAL', 'ISIN': 'MA0000012031'},
    {'name': 'M2M GROUP', 'ISIN': 'MA0000011678'},
    {'name': 'MAGHREB OXYGENE', 'ISIN': 'MA0000010985'},
    {'name': 'MAGHREBAIL', 'ISIN': 'MA0000011215'},
    {'name': 'MANAGEM', 'ISIN': 'MA0000011058'},
    {'name': 'MAROC LEASING', 'ISIN': 'MA0000010035'},
    {'name': 'MAROC TELECOM', 'ISIN': 'MA0000011488'},
    {'name': 'MICRODATA', 'ISIN': 'MA0000012163'},
    {'name': 'MUTANDIS', 'ISIN': 'MA0000012395'},
    {'name': 'OULMES', 'ISIN': 'MA0000010415'},
    {'name': 'PROMOPHARM', 'ISIN': 'MA0000011660'},
    {'name': 'REBAB COMPANY', 'ISIN': 'MA0000010993'},
    {'name': 'RES.DAR SAADA', 'ISIN': 'MA0000012239'},
    {'name': 'RISMA', 'ISIN': 'MA0000011462'},
    {'name': 'S2M', 'ISIN': 'MA0000012106'},
    {'name': 'SANLAM MAROC', 'ISIN': 'MA0000012007'},
    {'name': 'SALAFIN', 'ISIN': 'MA0000011744'},
    {'name': 'SMI', 'ISIN': 'MA0000010068'},
    {'name': 'STOKVIS NORD AFR', 'ISIN': 'MA0000011843'},
    {'name': 'SNEP', 'ISIN': 'MA0000011728'},
    {'name': 'SODEP', 'ISIN': 'MA0000012312'},
    {'name': 'SONASID', 'ISIN': 'MA0000010019'},
    {'name': 'SOTHEMA', 'ISIN': 'MA0000012502'},
    {'name': 'SRM', 'ISIN': 'MA0000011595'},
    {'name': 'STE BOISSONS', 'ISIN': 'MA0000010365'},
    {'name': 'STROC INDUS', 'ISIN': 'MA0000012056'},
    {'name': 'TAQA MOROCCO', 'ISIN': 'MA0000012205'},
    {'name': 'TGCC', 'ISIN': 'MA0000012528'},
    {'name': 'TIMAR', 'ISIN': 'MA0000011686'},
    {'name': 'TOTAL MAROC', 'ISIN': 'MA0000012262'},
    {'name': 'UNIMER', 'ISIN': 'MA0000012023'},
    {'name': 'WAFA ASSUR', 'ISIN': 'MA0000010928'},
    {'name': 'ZELLIDJA', 'ISIN': 'MA0000010571'},
    {'name': 'MASI', 'ISIN': ''},
    {'name': 'MSI20', 'ISIN': ''}
]
    
def notation_value():
  return {'Addoha' : '9000' , 'AFMA' : '12200' , 'Afric Indus' : '11700' , 'Afriquia Gaz' : '7100' , 'Agma' : '6700' , 'Alliances' : '11200' , 'Aluminium Maroc' : '6600' , 'Aradei Capital' : '27' , 'ATLANTASANAD' : '10300' , 'Attijariwafa' : '8200' , 'Auto Hall' : '3200' , 'Auto Nejma' : '7000' , 'BALIMA' : '3300' , 'BOA' : '1100' , 'BCP' : '8000' , 'BMCI' : '5100' , 'Cartier Saada' : '8900' , 'CDM' : '3600'  , 'CIH' : '3100' , 'Ciments Maroc' : '4000' , 'CMT' : '11000' , 'Colorado' : '9200' , 'COSUMAR' : '4100' , 'CTM' : '2200' , 'Dari Couspate' : '8500' , 'Delattre Lev' : '10800' , 'Delta Holding' : '10900' , 'DISWAY' : '9700' , 'Ennakl' : '11300' , 'EQDOM' : '2300' , 'FENIE BROSSETTE' : '9300' , 'HPS' : '9600' , 'IBMaroc' : '7600' , 'Immr Invest' : '12' , 'INVOLYS' : '9500' , 'Jet Contractors' : '11600' , 'LABEL VIE' : '11100' , 'LafargeHolcim' : '3800' , 'Lesieur Cristal' : '4800' , 'M2M Group' : '10000' , 'Maghreb Oxygene' : '7200' , 'Maghrebail' : '1600' , 'Managem' : '7300' , 'Maroc Leasing' : '2500' , 'Maroc Telecom' : '8001' , 'Med Paper' : '6500' , 'Microdata' : '10600' , 'Mutandis' : '21' , 'Nexans Maroc' : '7400' , 'Oulmes' : '5200' , 'PROMOPHARM' : '9900' , 'Rebab Company' : '5300' , 'Res.Dar Saada' : '12000' , 'Risma' : '8700' , 'S2M' : '11800' , 'Sanlam Assurance' : '11400' , 'SALAFIN' : '10700' ,  'SMI' : '1500' , 'Stokvis Nord Afr' : '10500' , 'SNEP' : '9400' , 'SODEP' : '12300' , 'Sonasid' : '1300' , 'SOTHEMA' : '9800' , 'SRM' : '2000' , 'Ste Boissons' : '10400' , 'STROC Indus' : '11500' , 'TAQA Morocco' : '11900' , 'Timar' : '10100' , 'Total Maroc' : '12100' , 'Unimer' : '7500' , 'Wafa Assur' : '6400' , 'Zellidja' : '5800','Akdital':"35","Disty Technologis":"32","TGCC":"29"}

def ticker_from_name(full_name):
    """
    Extract ticker symbol from full company name
    """
    # Common ticker mappings based on your data
    ticker_mapping = {
        'ADDOHA': 'ADH',
        'AFMA': 'AFM', 
        'AFRIC INDUS': 'AFI',
        'AFRIQUIA GAZ': 'GAZ',
        'AGMA': 'AGM',
        'AKDITAL': 'AKT',
        'ALLIANCES': 'ADI',
        'ALUMINIUM MAROC': 'ALM',
        'ARADEI CAPITAL': 'ARD',
        'ATLANTASANAD': 'ATL',
        'ATTIJARIWAFA': 'ATW',
        'AUTO HALL': 'ATH',
        'AUTO NEJMA': 'ANE',
        'BALIMA': 'BAL',
        'BANK OF AFRICA': 'BOA',
        'BANQUE CENTRALE POPULAIRE': 'BCP',
        'BMCI': 'BCI',
        'CARTIER SAADA': 'CRS',
        'CREDIT DU MAROC': 'CDM',
        'CREDIT IMMOBILIER ET HOTELIER': 'CIH',
        'CIMENTS MAROC': 'CMA',
        'COMPAGNIE MINIERE DE TOUISSIT': 'CMT',
        'COLORADO': 'COL',
        'COSUMAR': 'CSR',
        'COMPAGNIE DE TRANSPORT AU MAROC': 'CTM',
        'DARI COUSPATE': 'DRI',
        'DELATTRE LEVIVIER MAROC': 'DLM',
        'DELTA HOLDING': 'DHO',
        'DISTY TECHNOLOG': 'DYT',
        'DISWAY': 'DWY',
        'ENNAKL': 'ENK',
        'EQDOM': 'EQD',
        'FENIE BROSSETTE': 'FBR',
        'HIGHTECH PAYMENT SYSTEMS': 'HPS',
        'IBMAROC': 'IBC',
        'IMMR INVEST': 'IMO',
        'INVOLYS': 'INV',
        'JET CONTRACTORS': 'JET',
        'LABEL VIE': 'LBV',
        'LAFARGEHOLCIM': 'LHM',
        'LESIEUR CRISTAL': 'LES',
        'M2M GROUP': 'M2M',
        'MAGHREB OXYGENE': 'MOX',
        'MAGHREBAIL': 'MAB',
        'MANAGEM': 'MNG',
        'MAROC LEASING': 'MLE',
        'MAROC TELECOM': 'IAM',
        'MASI' : 'MASI',
        'MED PAPER': 'MDP',
        'MICRODATA': 'MIC',
        'MSI20': 'MSI20',
        'MUTANDIS': 'MUT',
        'OULMES': 'OUL',
        'PROMOPHARM': 'PMP',
        'REBAB COMPANY': 'REB',
        'RES.DAR SAADA': 'RDS',
        'RISMA': 'RIS',
        'S2M': 'S2M',
        'SANLAM MAROC': 'SLA',
        'SALAFIN': 'SLF',
        'SMI': 'SMI',
        'STOKVIS NORD AFR': 'SNA',
        'SNEP': 'SNP',
        'SODEP': 'SOD',
        'SONASID': 'SID',
        'SOTHEMA': 'SOT',
        'SRM': 'SRM',
        'STE BOISSONS': 'SBO',
        'STROC INDUS': 'STC',
        'TAQA MOROCCO': 'TQM',
        'TGCC': 'TGCC',
        'TIMAR': 'TIM',
        'TOTAL MAROC': 'TOT',
        'UNIMER': 'UMR',
        'WAFA ASSUR': 'WAA',
        'ZELLIDJA': 'ZEL'
    }

    ticker = ticker_mapping.get(full_name.upper())

    if ticker is None :
        if len(full_name) <= 7 and full_name.isalpha() and full_name.isupper() and full_name.upper() in ticker_mapping.values():
          ticker = full_name.upper()
    
    return ticker


def name_from_ticker(ticker):
    """
    Extract company name from ticker symbol
    """
    # Reverse mapping: ticker -> company name
    name_mapping = {
        'ADH': 'ADDOHA',
        'AFM': 'AFMA', 
        'AFI': 'AFRIC INDUS',
        'GAZ': 'AFRIQUIA GAZ',
        'AGM': 'AGMA',
        'AKT': 'AKDITAL',
        'ADI': 'ALLIANCES',
        'ALM': 'ALUMINIUM MAROC',
        'ARD': 'ARADEI CAPITAL',
        'ATL': 'ATLANTASANAD',
        'ATW': 'ATTIJARIWAFA',
        'ATH': 'AUTO HALL',
        'ANE': 'AUTO NEJMA',
        'BAL': 'BALIMA',
        'BOA': 'BANK OF AFRICA',
        'BCP': 'BANQUE CENTRALE POPULAIRE',
        'BCI': 'BMCI',
        'CRS': 'CARTIER SAADA',
        'CDM': 'CREDIT DU MAROC',
        'CIH': 'CREDIT IMMOBILIER ET HOTELIER',
        'CMA': 'CIMENTS MAROC',
        'CMT': 'COMPAGNIE MINIERE DE TOUISSIT',
        'COL': 'COLORADO',
        'CSR': 'COSUMAR',
        'CTM': 'COMPAGNIE DE TRANSPORT AU MAROC',
        'DRI': 'DARI COUSPATE',
        'DLM': 'DELATTRE LEVIVIER MAROC',
        'DHO': 'DELTA HOLDING',
        'DYT': 'DISTY TECHNOLOG',
        'DWY': 'DISWAY',
        'ENK': 'ENNAKL',
        'EQD': 'EQDOM',
        'FBR': 'FENIE BROSSETTE',
        'HPS': 'HIGHTECH PAYMENT SYSTEMS',
        'IBC': 'IBMAROC',
        'IMO': 'IMMR INVEST',
        'INV': 'INVOLYS',
        'JET': 'JET CONTRACTORS',
        'LBV': 'LABEL VIE',
        'LHM': 'LAFARGEHOLCIM',
        'LES': 'LESIEUR CRISTAL',
        'M2M': 'M2M GROUP',
        'MOX': 'MAGHREB OXYGENE',
        'MAB': 'MAGHREBAIL',
        'MNG': 'MANAGEM',
        'MLE': 'MAROC LEASING',
        'IAM': 'MAROC TELECOM',
        'MASI': 'MASI',
        'MDP': 'MED PAPER',
        'MIC': 'MICRODATA',
        'MSI20': 'MSI20',
        'MUT': 'MUTANDIS',
        'OUL': 'OULMES',
        'PMP': 'PROMOPHARM',
        'REB': 'REBAB COMPANY',
        'RDS': 'RES.DAR SAADA',
        'RIS': 'RISMA',
        'S2M': 'S2M',
        'SLA': 'SANLAM MAROC',
        'SLF': 'SALAFIN',
        'SMI': 'SMI',
        'SNA': 'STOKVIS NORD AFR',
        'SNP': 'SNEP',
        'SOD': 'SODEP',
        'SID': 'SONASID',
        'SOT': 'SOTHEMA',
        'SRM': 'SRM',
        'SBO': 'STE BOISSONS',
        'STC': 'STROC INDUS',
        'TQM': 'TAQA MOROCCO',
        'TGCC': 'TGCC',
        'TIM': 'TIMAR',
        'TOT': 'TOTAL MAROC',
        'UMR': 'UNIMER',
        'WAA': 'WAFA ASSUR',
        'ZEL': 'ZELLIDJA'
    }
    
    name = name_mapping.get(ticker.upper())
    
    if name is None:
        if len(ticker) <= 7 and ticker.isalpha() and ticker.isupper() and ticker.upper() in name_mapping.values():
            name = ticker.upper()
    
    return name
